#!/bin/bash
export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# clone chloroextractor repository into /tmp and extract the right VCS_REF
git clone https://github.com/chloroExtractorTeam/chloroExtractor.git /tmp/chloro
pushd /tmp/chloro
git checkout ${SOURCE_BRANCH}
export GIT_SHA1=$(git rev-parse HEAD)
popd

export VCS_REF=$(echo ${GIT_SHA1} | cut -b 1-7)

env

docker build \
       --build-arg VERSION=${SOURCE_BRANCH} \
       --build-arg VCS_REF=${VCS_REF} \
       --build-arg BUILD_DATE=${BUILD_DATE} \
       -t $IMAGE_NAME .
